#pragma once

#include <d3d9.h>

//=============================
//　テクスチャ構造体(enum)
//=============================
typedef enum 
{
	TEXTURE_INDEX_ROOF_STD,
	TEXTURE_INDEX_ROOF_BROKE,

	TEXTURE_INDEX_GOLDRANK,
	TEXTURE_INDEX_SILVERRANK,
	TEXTURE_INDEX_BLONZERANK,
	TEXTURE_INDEX_RESULT_BG,
	TEXTURE_INDEX_RANKING_BG,
	TEXTURE_INDEX_TITLE_LOGO,
	TEXTURE_INDEX_TITLE_BG,
	TEXTURE_INDEX_SKIP_SCENE_CHANGE,
	TEXTURE_INDEX_GAME_SCENE_CHANGE,
	TEXTURE_INDEX_HIT_EFFECT,
	TEXTURE_INDEX_AUDIENCE,

	TEXTURE_INDEX_WHATSCORE,
	TEXTURE_INDEX_PUSHUPPER,

	TEXTURE_INDEX_PUNCHINGMACHINE,
	TEXTURE_INDEX_GLOVE,
	TEXTURE_INDEX_SCENE_CHANGE_EFFECT,

	TEXTURE_INDEX_GOLDNUMBER,
	TEXTURE_INDEX_SILVERNUMBER,
	TEXTURE_INDEX_BLONZENUMBER,
	TEXTURE_INDEX_WHITENUMBER,

	TEXTURE_INDEX_DAMAGE_EFFECT,
	TEXTURE_INDEX_SLOW_EFFECT,
	TEXTURE_INDEX_CUT_THE_SKY_FRONT,
	TEXTURE_INDEX_CUT_THE_SKY_SIDE,

	TEXTURE_INDEX_GAUGE_CIRCLE,
	TEXTURE_INDEX_GAUGE_INSIDE,
	TEXTURE_INDEX_GAUGE_OUTSIDE,

    TEXTURE_INDEX_MAX
}TextureIndex;

int LoadTexture(void); //初期化
void UninitTexture(void); //終了処理
LPDIRECT3DTEXTURE9 Texture_GetTexture(TextureIndex index);
int Texture_GetWidth(TextureIndex index);
int Texture_GetHeight(TextureIndex index);
